services:
  unopim-web:
    build:
      context: .
      dockerfile: dockerfiles/web.Dockerfile
    container_name: unopim-web
    environment:
      COMPOSE_PROFILES: ${COMPOSE_PROFILES:-mysql}
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    restart: "no"

  unopim-mysql:
    image: mysql:8
    container_name: unopim-mysql
    profiles:
      - mysql
    volumes:
      - unopim-mysql-disk:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: unopim

  unopim-pgsql:
    image: postgres:16
    container_name: unopim-pgsql
    profiles:
      - pgsql
    volumes:
      - unopim-pgsql-disk:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: "no"
    environment:
      POSTGRES_DB: unopim
      POSTGRES_USER: unopim
      POSTGRES_PASSWORD: password

  unopim-q:
    build:
      context: .
      dockerfile: dockerfiles/q.Dockerfile
    container_name: unopim-q
    environment:
      COMPOSE_PROFILES: ${COMPOSE_PROFILES:-mysql}
    volumes:
      - .:/var/www/html
    restart: unless-stopped

  unopim-mailpit:
    image: 'axllent/mailpit:latest'
    container_name: unopim-mailpit
    restart: "no"
    ports:
      - "8025:8025"

# On-disk storage of DB data, when containers are stopped
volumes:
  unopim-mysql-disk: {}
  unopim-pgsql-disk: {}