<?php

namespace Webkul\AiAgent\Pipelines\Stages\Image;

use Webkul\AiAgent\Contracts\PipelineStageContract;
use Webkul\AiAgent\DTOs\AgentPayload;
use Webkul\AiAgent\DTOs\ImageProductContext;
use Webkul\AiAgent\Exceptions\PipelineException;

/**
 * Stage 5 — Evaluates how reliably each enriched attribute was detected
 * and assigns a per-field confidence score (0.0 – 1.0).
 *
 * Scoring is deterministic (no additional AI call) and is based on:
 *  - Whether the value originated from a direct vision detection
 *    (high confidence) vs. AI generation (medium) vs. a default fallback
 *    (low confidence).
 *  - Structural heuristics: non-empty strings, plausible lengths, etc.
 *
 * Reads from metadata:
 *   enrichedAttributes  — final merged attribute map
 *   enrichedKeys        — keys generated by EnrichmentStep (medium confidence)
 *   visionDetections    — original detection keys (high confidence)
 *
 * Reads from context (optional):
 *   confidenceThreshold  float  Mark for review below this value (default: 0.6)
 *
 * Writes to metadata:
 *   confidenceScores    array<string, float>  Per-key confidence (0.0 – 1.0)
 *   overallConfidence   float                 Mean of all per-key scores
 *   requiresReview      bool                  True if any key < confidenceThreshold
 *   lowConfidenceFields array<string>         Keys that fell below the threshold
 */
class ConfidenceScoreStep implements PipelineStageContract
{
    /**
     * Per-origin base confidence values.
     */
    protected const SCORE_VISION_DIRECT = 0.90;

    protected const SCORE_AI_ENRICHED = 0.65;

    protected const SCORE_DEFAULT = 0.35;

    /**
     * Attributes that are inherently hard to assess visually get a cap.
     *
     * @var array<string, float> attribute_code → max_score
     */
    protected const VISUAL_CONFIDENCE_CAPS = [
        'meta_title'        => 0.75,
        'meta_description'  => 0.75,
        'meta_keywords'     => 0.70,
        'target_audience'   => 0.70,
        'marketing_tagline' => 0.70,
    ];

    /**
     * {@inheritdoc}
     *
     * @throws PipelineException
     */
    public function handle(AgentPayload $payload, \Closure $next): AgentPayload
    {
        $enriched = $payload->metadata['enrichedAttributes'] ?? null;

        if (! is_array($enriched)) {
            throw new PipelineException(
                'ConfidenceScoreStep: enrichedAttributes is missing — EnrichmentStep must run first.',
                self::class,
            );
        }

        $threshold = (float) ($payload->context['confidenceThreshold'] ?? 0.6);
        $enrichedKeys = (array) ($payload->metadata['enrichedKeys'] ?? []);
        $visionDetection = (array) ($payload->metadata['visionDetections'] ?? []);

        // Build the set of keys that came from direct vision output
        $visionMappedKeys = $this->resolveVisionMappedKeys($visionDetection);

        $scores = [];
        $lowConfidence = [];

        foreach ($enriched as $key => $value) {
            $score = $this->scoreField($key, $value, $visionMappedKeys, $enrichedKeys);

            $scores[$key] = $score;

            if ($score < $threshold) {
                $lowConfidence[] = $key;
            }
        }

        $overall = empty($scores) ? 0.0 : array_sum($scores) / count($scores);
        $requiresReview = ! empty($lowConfidence);

        $ctx = ImageProductContext::fromArray($payload->metadata['imageContext'] ?? [])
            ->withConfidence($scores);

        return $next($payload->withMetadata([
            'imageContext'        => $ctx->toArray(),
            'confidenceScores'    => $scores,
            'overallConfidence'   => round($overall, 4),
            'requiresReview'      => $requiresReview,
            'lowConfidenceFields' => $lowConfidence,
        ]));
    }

    /**
     * Compute the confidence score for a single attribute field.
     *
     * @param  array<string>  $visionMappedKeys
     * @param  array<string>  $enrichedKeys
     */
    protected function scoreField(
        string $key,
        mixed $value,
        array $visionMappedKeys,
        array $enrichedKeys,
    ): float {
        // Determine base score from origin
        $base = match (true) {
            in_array($key, $visionMappedKeys, true) => self::SCORE_VISION_DIRECT,
            in_array($key, $enrichedKeys, true)     => self::SCORE_AI_ENRICHED,
            default                                 => self::SCORE_DEFAULT,
        };

        // Apply structural quality factors
        $base *= $this->qualityFactor($value);

        // Apply visual-confidence cap if applicable
        if (isset(self::VISUAL_CONFIDENCE_CAPS[$key])) {
            $base = min($base, self::VISUAL_CONFIDENCE_CAPS[$key]);
        }

        return round(min(max($base, 0.0), 1.0), 4);
    }

    /**
     * Return a multiplier (0.5 – 1.0) based on value quality heuristics.
     */
    protected function qualityFactor(mixed $value): float
    {
        if ($value === null || $value === '' || $value === []) {
            return 0.0;
        }

        if (is_array($value)) {
            // Penalise single-item arrays; reward richer arrays
            return count($value) === 1 ? 0.8 : 1.0;
        }

        $str = (string) $value;
        $length = mb_strlen(strip_tags($str));

        return match (true) {
            $length === 0   => 0.0,
            $length < 3     => 0.5,
            $length < 10    => 0.8,
            default         => 1.0,
        };
    }

    /**
     * Derive which PIM attribute keys are backed by direct vision detections.
     *
     * Uses the same default mapping as AttributeMappingStep so this stage
     * remains independent of it.
     *
     * @param  array<string, mixed>  $visionDetections
     * @return array<string>
     */
    protected function resolveVisionMappedKeys(array $visionDetections): array
    {
        $defaultMap = [
            'productType'         => 'product_type',
            'colors'              => 'color',
            'materials'           => 'material',
            'patterns'            => 'pattern',
            'style'               => 'style',
            'condition'           => 'condition',
            'brandIndicators'     => 'brand',
            'suggestedCategories' => 'categories',
            'rawDescription'      => 'description',
        ];

        $pimKeys = [];

        foreach (array_keys($visionDetections) as $detectionKey) {
            if (isset($defaultMap[$detectionKey])) {
                $pimKeys[] = $defaultMap[$detectionKey];
            }
        }

        return $pimKeys;
    }
}
