<?php

namespace Webkul\MagicAI\Services;

use GuzzleHttp\Client;
use Webkul\MagicAI\Contracts\LLMModelInterface;

class Gemini implements LLMModelInterface
{
    /**
     * New service instance.
     */
    public function __construct(
        protected string $model,
        protected string $prompt,
        protected float $temperature,
        protected bool $stream,
        protected bool $raw,
        protected int $maxTokens,
        protected string $systemPrompt,
    ) {}

    /**
     * Format the models response for Gemini AI.
     */
    public static function formatModelsResponse(array $data): array
    {
        $formattedModels = [];
        foreach (($data['models'] ?? []) as $model) {
            $formattedModels[] = [
                'id'    => $model['name'],
                'label' => $model['name'],
            ];
        }

        return $formattedModels;
    }

    /**
     * Set LLM prompt text.
     */
    public function ask(): string
    {
        $httpClient = new Client;
        $apiKey = core()->getConfigData('general.magic_ai.settings.api_key');
        $endpoint = "https://generativelanguage.googleapis.com/v1beta/models/{$this->model}:generateContent";

        $response = $httpClient->post($endpoint, [
            'headers' => [
                'Accept'         => 'application/json',
                'Content-Type'   => 'application/json',
                'x-goog-api-key' => $apiKey,
            ],
            'json' => [
                'contents' => [
                    ['parts' => [['text' => $this->prompt]]],
                ],
                'generationConfig' => [
                    'temperature'     => $this->temperature,
                    'maxOutputTokens' => $this->maxTokens,
                ],
            ],
        ]);

        $data = json_decode($response->getBody()->getContents(), true);

        return $data['candidates'][0]['content']['parts'][0]['text'] ?? 'No response';
    }

    /**
     * Generate image using Gemini.
     */
    public function images(array $options = []): array
    {
        $httpClient = new Client;

        $apiKey = core()->getConfigData('general.magic_ai.settings.api_key');

        if (! $apiKey) {
            throw new \RuntimeException('Gemini API key is missing.');
        }

        $endpoint = "https://generativelanguage.googleapis.com/v1beta/models/{$this->model}:generateContent?key={$apiKey}";

        $response = $httpClient->post($endpoint, [
            'headers' => [
                'Accept'         => 'application/json',
                'Content-Type'   => 'application/json',
            ],
            'json' => [
                'contents' => [
                    [
                        'parts' => [
                            ['text' => $this->prompt],
                        ],
                    ],
                ],
                'generationConfig' => [
                    'responseModalities' => ['IMAGE'],
                ],
            ],
        ]);

        $data = json_decode($response->getBody()->getContents(), true);

        $images = [];

        foreach ($data['candidates'] ?? [] as $candidate) {
            foreach ($candidate['content']['parts'] ?? [] as $part) {
                if (! empty($part['inlineData']['data'])) {
                    $mime = $part['inlineData']['mimeType'] ?? 'image/png';

                    $images[]['url'] = sprintf(
                        'data:%s;base64,%s',
                        $mime,
                        $part['inlineData']['data']
                    );
                }
            }
        }

        if (empty($images)) {
            throw new \RuntimeException('No image generated by Gemini.');
        }

        return $images;
    }
}
