<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $driver = DB::getDriverName();

        switch ($driver) {
            case 'mysql':
                Schema::table('oauth_clients', function (Blueprint $table) {
                    $table->uuid('id')->change();
                });
                break;

            case 'pgsql':
                DB::statement('ALTER TABLE oauth_clients ALTER COLUMN id DROP DEFAULT;');
                DB::statement('ALTER TABLE oauth_clients ALTER COLUMN id TYPE uuid USING md5(id::text)::uuid;');
                DB::statement('ALTER TABLE oauth_clients ALTER COLUMN id DROP DEFAULT;');
                break;
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $driver = DB::getDriverName();

        switch ($driver) {
            case 'mysql':
                Schema::table('oauth_clients', function (Blueprint $table) {
                    $table->bigIncrements('id')->change();
                });
                break;

            case 'pgsql':
                DB::statement('ALTER TABLE oauth_clients ALTER COLUMN id DROP DEFAULT;');
                DB::statement('ALTER TABLE oauth_clients ALTER COLUMN id TYPE bigint USING 1;');
                DB::statement('ALTER TABLE oauth_clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;');
                break;
        }
    }
};
