<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $driver = DB::getDriverName();

        switch ($driver) {
            case 'mysql':
                Schema::table('oauth_clients', function (Blueprint $table) {
                    $table->uuid('id')->change();
                });
                break;

            case 'pgsql':
                $tablePrefix = DB::getTablePrefix();

                DB::statement("ALTER TABLE {$tablePrefix}oauth_clients ALTER COLUMN id DROP DEFAULT;");
                DB::statement("ALTER TABLE {$tablePrefix}oauth_clients ALTER COLUMN id TYPE uuid USING md5(id::text)::uuid;");
                DB::statement("ALTER TABLE {$tablePrefix}oauth_clients ALTER COLUMN id DROP DEFAULT;");
                break;

            case 'sqlite':
                // SQLite doesn't support changing column types directly
                // For SQLite tests, we need to drop and recreate the table with UUID id
                DB::statement('DROP TABLE IF EXISTS oauth_clients');
                DB::statement('
                    CREATE TABLE IF NOT EXISTS oauth_clients (
                        id varchar not null primary key,
                        user_id integer nullable,
                        name varchar not null,
                        secret varchar(100) nullable,
                        provider varchar nullable,
                        redirect text not null,
                        personal_access_client tinyint(1) not null,
                        password_client tinyint(1) not null,
                        revoked tinyint(1) not null,
                        tenant_id integer nullable,
                        created_at datetime,
                        updated_at datetime
                    )
                ');
                Schema::create('oauth_clients', function (Blueprint $table) {
                    $table->uuid('id')->primary();
                    $table->unsignedBigInteger('user_id')->nullable()->index();
                    $table->string('name');
                    $table->string('secret', 100)->nullable();
                    $table->string('provider')->nullable();
                    $table->text('redirect');
                    $table->boolean('personal_access_client');
                    $table->boolean('password_client');
                    $table->boolean('revoked');
                    $table->unsignedBigInteger('tenant_id')->nullable();
                    $table->timestamps();
                });
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $driver = DB::getDriverName();

        switch ($driver) {
            case 'mysql':
                Schema::table('oauth_clients', function (Blueprint $table) {
                    $table->bigIncrements('id')->change();
                });
                break;

            case 'pgsql':
                $tablePrefix = DB::getTablePrefix();

                DB::statement("ALTER TABLE {$tablePrefix}oauth_clients ALTER COLUMN id DROP DEFAULT;");
                DB::statement("ALTER TABLE {$tablePrefix}oauth_clients ALTER COLUMN id TYPE bigint USING 1;");
                DB::statement("ALTER TABLE {$tablePrefix}oauth_clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;");
                break;

            case 'sqlite':
                // Revert back to integer id for SQLite
                Schema::dropIfExists('oauth_clients');

                Schema::create('oauth_clients', function (Blueprint $table) {
                    $table->bigIncrements('id');
                    $table->unsignedBigInteger('user_id')->nullable()->index();
                    $table->string('name');
                    $table->string('secret', 100)->nullable();
                    $table->string('provider')->nullable();
                    $table->text('redirect');
                    $table->boolean('personal_access_client');
                    $table->boolean('password_client');
                    $table->boolean('revoked');
                    $table->unsignedBigInteger('tenant_id')->nullable();
                    $table->timestamps();
                });
                break;
        }
    }
};
