export const scenarioTypes = [
  'Smoke Tests',
  'Sanity Tests',
  'Regression Tests',
  'End-to-End Tests',
  'Positive Test Cases',
  'Negative Test Cases',
  'Boundary Value Analysis',
  'Equivalence Partitioning',
  'Exploratory Scenarios',
  'Security Test Cases',
  'Accessibility Test Cases',
  'Responsive Test Cases',
  'Browser Compatibility Tests',
  'API Validation Tests',
  'Database Validation',
  'Performance Validation',
  'Session Validation',
  'Authorization Validation',
  'Authentication Validation',
  'File Upload Validation',
  'Image Validation',
  'CSV Import Validation',
  'Excel Import Validation',
  'Export Validation',
  'Pagination',
  'Search',
  'Filters',
  'Sorting',
  'Bulk Actions',
  'Keyboard Navigation',
  'Error Handling',
  'Exception Handling',
  'Validation Messages',
  'Toast Messages',
  'Modal Dialogs',
  'Confirmation Popups',
  'Network Failure',
  'Retry Scenarios',
  'Session Timeout',
  'Concurrent User Testing'
] as const;
