CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE IF NOT EXISTS "admin_password_resets" ("email" varchar not null, "token" varchar not null, "created_at" datetime, "tenant_id" integer);
CREATE INDEX "admin_password_resets_email_index" on "admin_password_resets" ("email");
CREATE TABLE IF NOT EXISTS "password_resets" ("email" varchar not null, "token" varchar not null, "created_at" datetime);
CREATE INDEX "password_resets_email_index" on "password_resets" ("email");
CREATE TABLE IF NOT EXISTS "oauth_auth_codes" ("id" varchar not null, "user_id" integer not null, "client_id" integer not null, "scopes" text, "revoked" tinyint(1) not null, "expires_at" datetime, primary key ("id"));
CREATE INDEX "oauth_auth_codes_user_id_index" on "oauth_auth_codes" ("user_id");
CREATE TABLE IF NOT EXISTS "oauth_access_tokens" ("id" varchar not null, "user_id" integer, "client_id" integer not null, "name" varchar, "scopes" text, "revoked" tinyint(1) not null, "created_at" datetime, "updated_at" datetime, "expires_at" datetime, "tenant_id" integer, primary key ("id"));
CREATE INDEX "oauth_access_tokens_user_id_index" on "oauth_access_tokens" ("user_id");
CREATE TABLE IF NOT EXISTS "oauth_refresh_tokens" ("id" varchar not null, "access_token_id" varchar not null, "revoked" tinyint(1) not null, "expires_at" datetime, "tenant_id" integer, primary key ("id"));
CREATE INDEX "oauth_refresh_tokens_access_token_id_index" on "oauth_refresh_tokens" ("access_token_id");
CREATE TABLE IF NOT EXISTS "oauth_clients" ("id" integer primary key autoincrement not null, "user_id" integer, "name" varchar not null, "secret" varchar, "provider" varchar, "redirect" text not null, "personal_access_client" tinyint(1) not null, "password_client" tinyint(1) not null, "revoked" tinyint(1) not null, "created_at" datetime, "updated_at" datetime, "tenant_id" integer);
CREATE INDEX "oauth_clients_user_id_index" on "oauth_clients" ("user_id");
CREATE TABLE IF NOT EXISTS "oauth_personal_access_clients" ("id" integer primary key autoincrement not null, "client_id" integer not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "roles" ("id" integer primary key autoincrement not null, "name" varchar not null, "description" varchar, "permission_type" varchar not null, "permissions" text, "created_at" datetime, "updated_at" datetime, "tenant_id" integer, "is_locked" tinyint(1) not null default '0', "code" varchar);
CREATE TABLE IF NOT EXISTS "attributes" ("id" integer primary key autoincrement not null, "code" varchar not null, "type" varchar not null, "swatch_type" varchar, "validation" varchar, "regex_pattern" varchar, "position" integer, "is_required" tinyint(1) not null default '0', "is_unique" tinyint(1) not null default '0', "value_per_locale" tinyint(1) not null default '0', "value_per_channel" tinyint(1) not null default '0', "default_value" varchar, "enable_wysiwyg" tinyint(1) not null default '0', "usable_in_grid" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, "is_filterable" tinyint(1) not null default '0', "ai_translate" tinyint(1) not null default '0', "tenant_id" integer);
CREATE INDEX "attributes_code_index" on "attributes" ("code");
CREATE INDEX "attributes_type_index" on "attributes" ("type");
CREATE INDEX "attributes_code_type_index" on "attributes" ("code", "type");
CREATE TABLE IF NOT EXISTS "attribute_families" ("id" integer primary key autoincrement not null, "code" varchar not null, "status" tinyint(1) not null default '0', "tenant_id" integer);
CREATE TABLE IF NOT EXISTS "attribute_groups" ("id" integer primary key autoincrement not null, "code" varchar not null, "is_user_defined" tinyint(1) not null default '1', "tenant_id" integer);
CREATE TABLE IF NOT EXISTS "attribute_options" ("id" integer primary key autoincrement not null, "attribute_id" integer not null, "code" varchar not null, "sort_order" integer, "swatch_value" varchar, "tenant_id" integer, foreign key("attribute_id") references "attributes"("id") on delete cascade);
CREATE UNIQUE INDEX "unique_code_attribute_id_index" on "attribute_options" ("code", "attribute_id");
CREATE TABLE IF NOT EXISTS "categories" ("id" integer primary key autoincrement not null, "code" varchar not null, "_lft" integer not null default '0', "_rgt" integer not null default '0', "parent_id" integer, "created_at" datetime, "updated_at" datetime, "additional_data" text, "tenant_id" integer);
CREATE INDEX "categories__lft__rgt_parent_id_index" on "categories" ("_lft", "_rgt", "parent_id");
CREATE INDEX "categories_code_index" on "categories" ("code");
CREATE TABLE IF NOT EXISTS "locales" ("id" integer primary key autoincrement not null, "code" varchar not null, "status" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, "tenant_id" integer);
CREATE TABLE IF NOT EXISTS "currencies" ("id" integer primary key autoincrement not null, "code" varchar not null, "symbol" varchar, "status" tinyint(1) not null default '0', "decimal" integer not null default '2', "created_at" datetime, "updated_at" datetime, "tenant_id" integer);
CREATE TABLE IF NOT EXISTS "channels" ("id" integer primary key autoincrement not null, "code" varchar not null, "root_category_id" integer, "created_at" datetime, "updated_at" datetime, "tenant_id" integer, foreign key("root_category_id") references "categories"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "channel_locales" ("channel_id" integer not null, "locale_id" integer not null, foreign key("channel_id") references "channels"("id") on delete cascade, foreign key("locale_id") references "locales"("id") on delete cascade, primary key ("channel_id", "locale_id"));
CREATE TABLE IF NOT EXISTS "channel_currencies" ("channel_id" integer not null, "currency_id" integer not null, foreign key("channel_id") references "channels"("id") on delete cascade, foreign key("currency_id") references "currencies"("id") on delete cascade, primary key ("channel_id", "currency_id"));
CREATE TABLE IF NOT EXISTS "products" ("id" integer primary key autoincrement not null, "sku" varchar not null, "type" varchar not null, "parent_id" integer, "attribute_family_id" integer, "values" text, "additional" text, "created_at" datetime, "updated_at" datetime, "status" tinyint(1) not null default '1', "avg_completeness_score" integer, "tenant_id" integer, foreign key("attribute_family_id") references "attribute_families"("id") on delete restrict);
CREATE INDEX "products_sku_index" on "products" ("sku");
CREATE INDEX "products_type_index" on "products" ("type");
CREATE INDEX "products_attribute_family_id_index" on "products" ("attribute_family_id");
CREATE INDEX "products_parent_id_index" on "products" ("parent_id");
CREATE INDEX "attribute_family_parent_idx" on "products" ("attribute_family_id", "parent_id");
CREATE TABLE IF NOT EXISTS "product_relations" ("parent_id" integer not null, "child_id" integer not null, "tenant_id" integer, foreign key("parent_id") references "products"("id") on delete cascade, foreign key("child_id") references "products"("id") on delete cascade);
CREATE UNIQUE INDEX "product_relations_parent_id_child_id_unique" on "product_relations" ("parent_id", "child_id");
CREATE TABLE IF NOT EXISTS "product_super_attributes" ("product_id" integer not null, "attribute_id" integer not null, "tenant_id" integer, foreign key("product_id") references "products"("id") on delete cascade, foreign key("attribute_id") references "attributes"("id") on delete restrict);
CREATE UNIQUE INDEX "product_super_attributes_product_id_attribute_id_unique" on "product_super_attributes" ("product_id", "attribute_id");
CREATE TABLE IF NOT EXISTS "core_config" ("id" integer primary key autoincrement not null, "code" varchar not null, "value" text not null, "channel_code" varchar, "locale_code" varchar, "created_at" datetime, "updated_at" datetime, "tenant_id" integer);
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE TABLE IF NOT EXISTS "channel_translations" ("id" integer primary key autoincrement not null, "channel_id" integer not null, "locale" varchar not null, "name" varchar not null, "created_at" datetime, "updated_at" datetime, "tenant_id" integer, foreign key("channel_id") references "channels"("id") on delete cascade);
CREATE UNIQUE INDEX "channel_translations_channel_id_locale_unique" on "channel_translations" ("channel_id", "locale");
CREATE INDEX "channel_translations_locale_index" on "channel_translations" ("locale");
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "admins" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "password" varchar, "api_token" varchar, "status" tinyint(1) not null default '0', "role_id" integer not null, "image" varchar, "timezone" varchar not null default 'UTC', "ui_locale_id" integer, "remember_token" varchar, "created_at" datetime, "updated_at" datetime, "tenant_id" integer, foreign key("ui_locale_id") references "locales"("id"));
CREATE UNIQUE INDEX "admins_api_token_unique" on "admins" ("api_token");
CREATE TABLE IF NOT EXISTS "category_fields" ("id" integer primary key autoincrement not null, "code" varchar not null, "type" varchar not null, "validation" varchar, "position" integer, "is_required" tinyint(1) not null default '0', "is_unique" tinyint(1) not null default '0', "status" tinyint(1) not null default '0', "section" varchar not null, "value_per_locale" tinyint(1) not null default '0', "enable_wysiwyg" tinyint(1) not null default '0', "regex_pattern" varchar, "created_at" datetime, "updated_at" datetime, "tenant_id" integer);
CREATE INDEX "category_fields_code_index" on "category_fields" ("code");
CREATE INDEX "category_fields_type_index" on "category_fields" ("type");
CREATE INDEX "category_fields_status_index" on "category_fields" ("status");
CREATE INDEX "category_fields_section_index" on "category_fields" ("section");
CREATE TABLE IF NOT EXISTS "category_field_options" ("id" integer primary key autoincrement not null, "code" varchar, "sort_order" integer, "category_field_id" integer not null, "tenant_id" integer, foreign key("category_field_id") references "category_fields"("id") on delete cascade);
CREATE UNIQUE INDEX "unique_code_category_field_id_index" on "category_field_options" ("code", "category_field_id");
CREATE TABLE IF NOT EXISTS "audits" ("id" integer primary key autoincrement not null, "user_type" varchar, "user_id" integer, "event" varchar not null, "auditable_type" varchar not null, "auditable_id" integer not null, "old_values" text, "new_values" text, "url" text, "ip_address" varchar, "user_agent" varchar, "tags" varchar, "created_at" datetime, "updated_at" datetime, "version_id" integer, "history_id" integer, "tenant_id" integer);
CREATE INDEX "audits_auditable_type_auditable_id_index" on "audits" ("auditable_type", "auditable_id");
CREATE INDEX "audits_user_id_user_type_index" on "audits" ("user_id", "user_type");
CREATE TABLE IF NOT EXISTS "attribute_family_group_mappings" ("id" integer primary key autoincrement not null, "attribute_family_id" integer not null, "attribute_group_id" integer not null, "position" integer, "tenant_id" integer, foreign key("attribute_family_id") references "attribute_families"("id") on delete cascade, foreign key("attribute_group_id") references "attribute_groups"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "attribute_group_mappings" ("attribute_id" integer not null, "attribute_family_group_id" integer not null, "position" integer, "tenant_id" integer, foreign key("attribute_id") references "attributes"("id") on delete cascade, foreign key("attribute_family_group_id") references "attribute_family_group_mappings"("id") on delete cascade, primary key ("attribute_id", "attribute_family_group_id"));
CREATE TABLE IF NOT EXISTS "job_track_batches" ("id" integer primary key autoincrement not null, "state" varchar not null default 'pending', "data" text not null, "summary" text, "job_track_id" integer not null, "tenant_id" integer, foreign key("job_track_id") references "job_track"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "api_keys" ("id" integer primary key autoincrement not null, "name" varchar not null, "admin_id" integer not null, "oauth_client_id" varchar, "permission_type" varchar not null, "revoked" tinyint(1) not null, "permissions" text, "created_at" datetime, "updated_at" datetime, "tenant_id" integer, foreign key("admin_id") references "admins"("id") on delete cascade);
CREATE INDEX "api_keys_oauth_client_id_index" on "api_keys" ("oauth_client_id");
CREATE TABLE IF NOT EXISTS "wk_shopify_credentials_config" ("id" integer primary key autoincrement not null, "shopUrl" varchar not null, "accessToken" varchar not null, "active" tinyint(1) not null default '0', "apiVersion" varchar, "storelocaleMapping" text, "storeLocales" text, "defaultSet" tinyint(1) not null default '0', "resources" varchar, "extras" text, "created_at" datetime, "updated_at" datetime, "tenant_id" integer);
CREATE TABLE IF NOT EXISTS "shopify_setting_configuration_values" ("id" integer primary key autoincrement not null, "mapping" text, "extras" text, "created_at" datetime, "updated_at" datetime, "tenant_id" integer);
CREATE TABLE IF NOT EXISTS "wk_shopify_data_mapping" ("id" integer primary key autoincrement not null, "entityType" varchar, "code" varchar, "externalId" varchar, "relatedId" varchar, "jobInstanceId" integer not null, "relatedSource" varchar, "apiUrl" varchar, "created_at" datetime, "updated_at" datetime, "tenant_id" integer);
CREATE TABLE IF NOT EXISTS "user_notifications" ("id" integer primary key autoincrement not null, "admin_id" integer, "notification_id" integer, "read" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, "tenant_id" integer, foreign key("notification_id") references "notifications"("id") on delete cascade, foreign key("admin_id") references "admins"("id") on delete cascade);
CREATE TABLE notifications (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, type VARCHAR(255) NOT NULL COLLATE "BINARY", created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, "tenant_id" integer);
CREATE INDEX "products_status_index" on "products" ("status");
CREATE TABLE IF NOT EXISTS "wk_shopify_metafield_defination" ("id" integer primary key autoincrement not null, "code" varchar not null, "attribute" varchar not null, "name_space" varchar not null, "name_space_key" varchar not null, "description" varchar not null, "type" varchar not null, "ownerType" varchar not null, "validations" text, "pin" tinyint(1) not null default '0', "listvalue" tinyint(1) not null default '0', "ContentTypeName" varchar not null, "ownerTypeName" varchar not null, "attributeLabel" varchar not null, "options" text, "storefronts" tinyint(1) not null default '1', "apiUrl" text, "created_at" datetime, "updated_at" datetime, "tenant_id" integer);
CREATE TABLE category_field_option_translations (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, category_field_option_id INTEGER NOT NULL, locale VARCHAR(255) NOT NULL, label VARCHAR(255) DEFAULT NULL, "tenant_id" integer, FOREIGN KEY (category_field_option_id) REFERENCES category_field_options (id) ON UPDATE NO ACTION ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE UNIQUE INDEX fields_options_locale_unique ON category_field_option_translations (category_field_option_id, locale);
CREATE INDEX IDX_442B2A231A4EC7B7 ON category_field_option_translations (category_field_option_id);
CREATE INDEX "category_field_option_translations_label" on "category_field_option_translations" ("label");
CREATE TABLE category_field_translations (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, category_field_id INTEGER NOT NULL, locale VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, "tenant_id" integer, FOREIGN KEY (category_field_id) REFERENCES category_fields (id) ON UPDATE NO ACTION ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE INDEX category_field_translations_locale_category_field_id_index ON category_field_translations (locale, category_field_id);
CREATE INDEX category_field_translations_category_field_id_index ON category_field_translations (category_field_id);
CREATE UNIQUE INDEX category_field_translations_category_field_id_locale_unique ON category_field_translations (category_field_id, locale);
CREATE INDEX "category_field_translations_name" on "category_field_translations" ("name");
CREATE TABLE attribute_family_translations (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, attribute_family_id INTEGER NOT NULL, locale VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, "tenant_id" integer, FOREIGN KEY (attribute_family_id) REFERENCES attribute_families (id) ON UPDATE NO ACTION ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE UNIQUE INDEX attribute_family_translations_attribute_family_id_locale_unique ON attribute_family_translations (attribute_family_id, locale);
CREATE INDEX IDX_1E0CF9217E7F26EC ON attribute_family_translations (attribute_family_id);
CREATE INDEX "attribute_family_translations_name_locale_attribute_family_id" on "attribute_family_translations" ("name", "attribute_family_id");
CREATE INDEX "attribute_family_translations_name" on "attribute_family_translations" ("name");
CREATE TABLE attribute_group_translations (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, attribute_group_id INTEGER NOT NULL, locale VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, "tenant_id" integer, FOREIGN KEY (attribute_group_id) REFERENCES attribute_groups (id) ON UPDATE NO ACTION ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE UNIQUE INDEX attribute_group_translations_attribute_group_id_locale_unique ON attribute_group_translations (attribute_group_id, locale);
CREATE INDEX IDX_5C704A6862D643B7 ON attribute_group_translations (attribute_group_id);
CREATE INDEX "attribute_group_translations_name" on "attribute_group_translations" ("name");
CREATE TABLE attribute_translations (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, attribute_id INTEGER NOT NULL, locale VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, "tenant_id" integer, FOREIGN KEY (attribute_id) REFERENCES attributes (id) ON UPDATE NO ACTION ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE INDEX attribute_translations_locale_attribute_id_index ON attribute_translations (locale, attribute_id);
CREATE INDEX attribute_translations_attribute_id_index ON attribute_translations (attribute_id);
CREATE UNIQUE INDEX attribute_translations_attribute_id_locale_unique ON attribute_translations (attribute_id, locale);
CREATE INDEX "attribute_translations_attribute_id_name" on "attribute_translations" ("name", "attribute_id");
CREATE INDEX "attribute_translations_name" on "attribute_translations" ("name");
CREATE TABLE attribute_option_translations (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, attribute_option_id INTEGER NOT NULL, locale VARCHAR(255) NOT NULL, label VARCHAR(255) DEFAULT NULL, "tenant_id" integer, FOREIGN KEY (attribute_option_id) REFERENCES attribute_options (id) ON UPDATE NO ACTION ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE UNIQUE INDEX attribute_option_translations_attribute_option_id_locale_unique ON attribute_option_translations (attribute_option_id, locale);
CREATE INDEX IDX_655B6F701AE56DE9 ON attribute_option_translations (attribute_option_id);
CREATE INDEX "attribute_option_translations_option_id_label" on "attribute_option_translations" ("label", "attribute_option_id");
CREATE INDEX "attribute_option_translations_label" on "attribute_option_translations" ("label");
CREATE TABLE IF NOT EXISTS "magic_ai_prompts" ("id" integer primary key autoincrement not null, "title" varchar not null, "prompt" text not null, "type" varchar check ("type" in ('product', 'category')) not null, "created_at" datetime, "updated_at" datetime, "tone" integer, "tenant_id" integer);
CREATE TABLE IF NOT EXISTS "completeness_settings" ("id" integer primary key autoincrement not null, "family_id" integer not null, "attribute_id" integer not null, "channel_id" integer not null, "created_at" datetime, "updated_at" datetime, "tenant_id" integer, foreign key("family_id") references "attribute_families"("id") on delete cascade, foreign key("attribute_id") references "attributes"("id") on delete cascade, foreign key("channel_id") references "channels"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "product_completeness" ("id" integer primary key autoincrement not null, "product_id" integer not null, "channel_id" integer not null, "locale_id" integer not null, "score" integer not null, "missing_count" integer not null, "created_at" datetime, "updated_at" datetime, "tenant_id" integer, foreign key("product_id") references "products"("id") on delete cascade, foreign key("channel_id") references "channels"("id") on delete cascade, foreign key("locale_id") references "locales"("id") on delete cascade);
CREATE UNIQUE INDEX "product_completeness_product_id_channel_id_locale_id_unique" on "product_completeness" ("product_id", "channel_id", "locale_id");
CREATE TABLE IF NOT EXISTS "magic_ai_system_prompts" ("id" integer primary key autoincrement not null, "title" varchar not null, "tone" text not null, "max_tokens" integer not null, "temperature" float not null, "is_enabled" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, "tenant_id" integer);
CREATE TABLE IF NOT EXISTS "webhook_logs" ("id" integer primary key autoincrement not null, "sku" varchar not null, "user" varchar not null, "status" tinyint(1) not null, "extra" text, "created_at" datetime, "updated_at" datetime, "tenant_id" integer);
CREATE TABLE IF NOT EXISTS "webhook_settings" ("id" integer primary key autoincrement not null, "field" varchar not null, "value" varchar, "extra" text, "created_at" datetime, "updated_at" datetime, "tenant_id" integer);
CREATE TABLE job_instances (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, code VARCHAR(255) NOT NULL, entity_type VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, "action" VARCHAR(255) NOT NULL, validation_strategy VARCHAR(255) NOT NULL, allowed_errors INTEGER DEFAULT 0 NOT NULL, field_separator CHAR(1) DEFAULT NULL, file_path VARCHAR(191) DEFAULT NULL, images_directory_path VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, filters CLOB DEFAULT NULL --(DC2Type:json)
, "tenant_id" integer);
CREATE TABLE job_track (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, job_instances_id INTEGER NOT NULL, user_id INTEGER DEFAULT NULL, state VARCHAR(255) DEFAULT 'pending' NOT NULL, type VARCHAR(255) NOT NULL, "action" VARCHAR(255) NOT NULL, validation_strategy VARCHAR(255) NOT NULL, allowed_errors INTEGER DEFAULT 0 NOT NULL, processed_rows_count INTEGER DEFAULT 0 NOT NULL, invalid_rows_count INTEGER DEFAULT 0 NOT NULL, errors_count INTEGER DEFAULT 0 NOT NULL, errors CLOB DEFAULT NULL, field_separator CHAR(1) DEFAULT NULL, file_path VARCHAR(191) DEFAULT NULL, images_directory_path VARCHAR(255) DEFAULT NULL, error_file_path VARCHAR(255) DEFAULT NULL, summary CLOB DEFAULT NULL, meta CLOB NOT NULL, started_at DATETIME DEFAULT NULL, completed_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, "tenant_id" integer, FOREIGN KEY (job_instances_id) REFERENCES job_instances (id) ON UPDATE NO ACTION ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, FOREIGN KEY (user_id) REFERENCES admins (id) ON UPDATE NO ACTION ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE INDEX IDX_D7BF45D68B2E15A1 ON job_track (job_instances_id);
CREATE INDEX IDX_D7BF45D6A76ED395 ON job_track (user_id);
CREATE TABLE IF NOT EXISTS "tenants" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "name" varchar not null, "domain" varchar not null, "status" varchar check ("status" in ('provisioning', 'active', 'suspended', 'deleting', 'deleted')) not null default 'provisioning', "settings" text, "es_index_uuid" varchar not null, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
CREATE UNIQUE INDEX "tenants_uuid_unique" on "tenants" ("uuid");
CREATE UNIQUE INDEX "tenants_domain_unique" on "tenants" ("domain");
CREATE UNIQUE INDEX "tenants_es_index_uuid_unique" on "tenants" ("es_index_uuid");
CREATE INDEX "products_tenant_id_id_index" on "products" ("tenant_id", "id");
CREATE INDEX "categories_tenant_id_id_index" on "categories" ("tenant_id", "id");
CREATE INDEX "attributes_tenant_id_id_index" on "attributes" ("tenant_id", "id");
CREATE INDEX "channels_tenant_id_id_index" on "channels" ("tenant_id", "id");
CREATE INDEX "admins_tenant_id_id_index" on "admins" ("tenant_id", "id");
CREATE INDEX "attribute_families_tenant_id_id_index" on "attribute_families" ("tenant_id", "id");
CREATE INDEX "attribute_groups_tenant_id_id_index" on "attribute_groups" ("tenant_id", "id");
CREATE INDEX "roles_tenant_id_id_index" on "roles" ("tenant_id", "id");
CREATE INDEX "locales_tenant_id_id_index" on "locales" ("tenant_id", "id");
CREATE INDEX "currencies_tenant_id_id_index" on "currencies" ("tenant_id", "id");
CREATE INDEX "core_config_tenant_id_id_index" on "core_config" ("tenant_id", "id");
CREATE INDEX "category_fields_tenant_id_id_index" on "category_fields" ("tenant_id", "id");
CREATE INDEX "category_field_options_tenant_id_id_index" on "category_field_options" ("tenant_id", "id");
CREATE INDEX "attribute_options_tenant_id_id_index" on "attribute_options" ("tenant_id", "id");
CREATE INDEX "api_keys_tenant_id_id_index" on "api_keys" ("tenant_id", "id");
CREATE INDEX "job_instances_tenant_id_id_index" on "job_instances" ("tenant_id", "id");
CREATE INDEX "job_track_tenant_id_id_index" on "job_track" ("tenant_id", "id");
CREATE INDEX "notifications_tenant_id_id_index" on "notifications" ("tenant_id", "id");
CREATE INDEX "user_notifications_tenant_id_id_index" on "user_notifications" ("tenant_id", "id");
CREATE INDEX "magic_ai_prompts_tenant_id_id_index" on "magic_ai_prompts" ("tenant_id", "id");
CREATE INDEX "magic_ai_system_prompts_tenant_id_id_index" on "magic_ai_system_prompts" ("tenant_id", "id");
CREATE INDEX "webhook_logs_tenant_id_id_index" on "webhook_logs" ("tenant_id", "id");
CREATE INDEX "webhook_settings_tenant_id_id_index" on "webhook_settings" ("tenant_id", "id");
CREATE INDEX "oauth_clients_tenant_id_id_index" on "oauth_clients" ("tenant_id", "id");
CREATE UNIQUE INDEX products_tenant_sku_unique ON products (tenant_id, sku);
CREATE UNIQUE INDEX "roles_code_unique" on "roles" ("code");
CREATE INDEX "job_track_batches_tenant_id_id_index" on "job_track_batches" ("tenant_id", "id");
CREATE INDEX "audits_tenant_id_id_index" on "audits" ("tenant_id", "id");
CREATE INDEX "attribute_translations_tenant_id_id_index" on "attribute_translations" ("tenant_id", "id");
CREATE INDEX "attribute_option_translations_tenant_id_id_index" on "attribute_option_translations" ("tenant_id", "id");
CREATE INDEX "attribute_family_translations_tenant_id_id_index" on "attribute_family_translations" ("tenant_id", "id");
CREATE INDEX "attribute_group_translations_tenant_id_id_index" on "attribute_group_translations" ("tenant_id", "id");
CREATE INDEX "category_field_translations_tenant_id_id_index" on "category_field_translations" ("tenant_id", "id");
CREATE INDEX "category_field_option_translations_tenant_id_id_index" on "category_field_option_translations" ("tenant_id", "id");
CREATE INDEX "channel_translations_tenant_id_id_index" on "channel_translations" ("tenant_id", "id");
CREATE INDEX "product_relations_tenant_id_index" on "product_relations" ("tenant_id");
CREATE INDEX "product_super_attributes_tenant_id_index" on "product_super_attributes" ("tenant_id");
CREATE INDEX "completeness_settings_tenant_id_id_index" on "completeness_settings" ("tenant_id", "id");
CREATE INDEX "product_completeness_tenant_id_id_index" on "product_completeness" ("tenant_id", "id");
CREATE UNIQUE INDEX categories_tenant_code_unique ON categories (tenant_id, code);
CREATE UNIQUE INDEX locales_tenant_code_unique ON locales (tenant_id, code);
CREATE UNIQUE INDEX attributes_tenant_code_unique ON attributes (tenant_id, code);
CREATE UNIQUE INDEX category_fields_tenant_code_unique ON category_fields (tenant_id, code);
CREATE UNIQUE INDEX admins_tenant_email_unique ON admins (tenant_id, email);
CREATE UNIQUE INDEX job_instances_tenant_code_unique ON job_instances (tenant_id, code);
CREATE INDEX "oauth_access_tokens_tenant_id_id_index" on "oauth_access_tokens" ("tenant_id", "id");
CREATE INDEX "oauth_refresh_tokens_tenant_id_id_index" on "oauth_refresh_tokens" ("tenant_id", "id");
CREATE INDEX "admin_password_resets_tenant_id_index" on "admin_password_resets" ("tenant_id");
CREATE INDEX "attribute_family_group_mappings_tenant_id_id_index" on "attribute_family_group_mappings" ("tenant_id", "id");
CREATE INDEX "attribute_group_mappings_tenant_id_index" on "attribute_group_mappings" ("tenant_id");
CREATE INDEX "wk_shopify_credentials_config_tenant_id_id_index" on "wk_shopify_credentials_config" ("tenant_id", "id");
CREATE INDEX "shopify_setting_configuration_values_tenant_id_id_index" on "shopify_setting_configuration_values" ("tenant_id", "id");
CREATE INDEX "wk_shopify_data_mapping_tenant_id_id_index" on "wk_shopify_data_mapping" ("tenant_id", "id");
CREATE INDEX "wk_shopify_metafield_defination_tenant_id_id_index" on "wk_shopify_metafield_defination" ("tenant_id", "id");
CREATE UNIQUE INDEX wk_shopify_credentials_config_tenant_shopurl_unique ON wk_shopify_credentials_config (tenant_id, shopUrl);
CREATE TABLE IF NOT EXISTS "channel_connectors" ("id" integer primary key autoincrement not null, "tenant_id" integer not null, "code" varchar not null, "name" varchar not null, "channel_type" varchar not null, "credentials" text, "settings" text, "status" varchar not null default 'disconnected', "last_synced_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("tenant_id") references "tenants"("id") on delete cascade);
CREATE INDEX "idx_connector_tenant_id" on "channel_connectors" ("tenant_id", "id");
CREATE INDEX "idx_connector_tenant_type" on "channel_connectors" ("tenant_id", "channel_type");
CREATE INDEX "idx_connector_status" on "channel_connectors" ("status");
CREATE UNIQUE INDEX idx_connector_tenant_code ON channel_connectors (tenant_id, code);
CREATE TABLE IF NOT EXISTS "channel_field_mappings" ("id" integer primary key autoincrement not null, "tenant_id" integer not null, "channel_connector_id" integer not null, "unopim_attribute_code" varchar not null, "channel_field" varchar not null, "direction" varchar not null default 'export', "transformation" text, "locale_mapping" text, "sort_order" integer not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("tenant_id") references "tenants"("id") on delete cascade, foreign key("channel_connector_id") references "channel_connectors"("id") on delete cascade);
CREATE INDEX "idx_field_mapping_tenant_id" on "channel_field_mappings" ("tenant_id", "id");
CREATE INDEX "idx_field_mapping_connector" on "channel_field_mappings" ("channel_connector_id");
CREATE UNIQUE INDEX idx_field_mapping_unique ON channel_field_mappings (channel_connector_id, unopim_attribute_code, channel_field);
CREATE TABLE IF NOT EXISTS "channel_sync_jobs" ("id" integer primary key autoincrement not null, "tenant_id" integer not null, "channel_connector_id" integer not null, "job_id" varchar not null, "status" varchar not null default 'pending', "sync_type" varchar not null, "total_products" integer not null default '0', "synced_products" integer not null default '0', "failed_products" integer not null default '0', "error_summary" text, "retry_of_id" integer, "started_at" datetime, "completed_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("tenant_id") references "tenants"("id") on delete cascade, foreign key("channel_connector_id") references "channel_connectors"("id") on delete cascade, foreign key("retry_of_id") references "channel_sync_jobs"("id") on delete set null);
CREATE INDEX "idx_sync_job_tenant_id" on "channel_sync_jobs" ("tenant_id", "id");
CREATE INDEX "idx_sync_job_tenant_status" on "channel_sync_jobs" ("tenant_id", "status");
CREATE INDEX "idx_sync_job_connector_created" on "channel_sync_jobs" ("channel_connector_id", "created_at");
CREATE INDEX "idx_sync_job_retry" on "channel_sync_jobs" ("retry_of_id");
CREATE UNIQUE INDEX idx_sync_job_tenant_job_id ON channel_sync_jobs (tenant_id, job_id);
CREATE TABLE IF NOT EXISTS "product_channel_mappings" ("id" integer primary key autoincrement not null, "tenant_id" integer not null, "channel_connector_id" integer not null, "product_id" integer not null, "external_id" varchar not null, "external_variant_id" varchar, "entity_type" varchar not null default 'product', "sync_status" varchar not null default 'pending', "last_synced_at" datetime, "data_hash" varchar, "meta" text, "created_at" datetime, "updated_at" datetime, foreign key("tenant_id") references "tenants"("id") on delete cascade, foreign key("channel_connector_id") references "channel_connectors"("id") on delete cascade, foreign key("product_id") references "products"("id") on delete cascade);
CREATE INDEX "idx_product_mapping_tenant_id" on "product_channel_mappings" ("tenant_id", "id");
CREATE INDEX "idx_product_mapping_connector_external" on "product_channel_mappings" ("channel_connector_id", "external_id");
CREATE INDEX "idx_product_mapping_status" on "product_channel_mappings" ("sync_status");
CREATE INDEX "idx_product_mapping_product" on "product_channel_mappings" ("product_id");
CREATE UNIQUE INDEX idx_product_mapping_unique ON product_channel_mappings (channel_connector_id, product_id, entity_type);
CREATE TABLE IF NOT EXISTS "channel_sync_conflicts" ("id" integer primary key autoincrement not null, "tenant_id" integer not null, "channel_connector_id" integer not null, "channel_sync_job_id" integer, "product_id" integer, "conflict_type" varchar not null, "conflicting_fields" text not null, "pim_modified_at" datetime, "channel_modified_at" datetime, "resolution_status" varchar not null default 'pending', "resolution_details" text, "resolved_by" integer, "resolved_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("tenant_id") references "tenants"("id") on delete cascade, foreign key("channel_connector_id") references "channel_connectors"("id") on delete cascade, foreign key("channel_sync_job_id") references "channel_sync_jobs"("id") on delete set null, foreign key("product_id") references "products"("id") on delete set null, foreign key("resolved_by") references "admins"("id") on delete set null);
CREATE INDEX "idx_conflict_tenant_id" on "channel_sync_conflicts" ("tenant_id", "id");
CREATE INDEX "idx_conflict_tenant_status" on "channel_sync_conflicts" ("tenant_id", "resolution_status");
CREATE INDEX "idx_conflict_connector" on "channel_sync_conflicts" ("channel_connector_id");
CREATE INDEX "idx_conflict_job" on "channel_sync_conflicts" ("channel_sync_job_id");
CREATE INDEX "idx_conflict_product" on "channel_sync_conflicts" ("product_id");
CREATE TABLE IF NOT EXISTS "channel_webhook_events" ("id" integer primary key autoincrement not null, "tenant_id" integer not null, "channel_connector_id" integer not null, "webhook_event_id" varchar, "event_type" varchar not null, "payload" text not null, "processed_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("tenant_id") references "tenants"("id") on delete cascade, foreign key("channel_connector_id") references "channel_connectors"("id") on delete cascade);
CREATE INDEX "idx_webhook_tenant_id" on "channel_webhook_events" ("tenant_id", "id");
CREATE INDEX "idx_webhook_tenant_connector" on "channel_webhook_events" ("tenant_id", "channel_connector_id");
CREATE UNIQUE INDEX "idx_webhook_unique_event" on "channel_webhook_events" ("tenant_id", "channel_connector_id", "webhook_event_id");
INSERT INTO migrations VALUES(1,'2014_10_12_100000_create_admin_password_resets_table',1);
INSERT INTO migrations VALUES(2,'2014_10_12_100000_create_password_resets_table',1);
INSERT INTO migrations VALUES(3,'2016_06_01_000001_create_oauth_auth_codes_table',1);
INSERT INTO migrations VALUES(4,'2016_06_01_000002_create_oauth_access_tokens_table',1);
INSERT INTO migrations VALUES(5,'2016_06_01_000003_create_oauth_refresh_tokens_table',1);
INSERT INTO migrations VALUES(6,'2016_06_01_000004_create_oauth_clients_table',1);
INSERT INTO migrations VALUES(7,'2016_06_01_000005_create_oauth_personal_access_clients_table',1);
INSERT INTO migrations VALUES(8,'2018_06_13_055341_create_roles_table',1);
INSERT INTO migrations VALUES(9,'2018_07_05_130148_create_attributes_table',1);
INSERT INTO migrations VALUES(10,'2018_07_05_132854_create_attribute_translations_table',1);
INSERT INTO migrations VALUES(11,'2018_07_05_135150_create_attribute_families_table',1);
INSERT INTO migrations VALUES(12,'2018_07_05_135152_create_attribute_groups_table',1);
INSERT INTO migrations VALUES(13,'2018_07_05_140832_create_attribute_options_table',1);
INSERT INTO migrations VALUES(14,'2018_07_05_140856_create_attribute_option_translations_table',1);
INSERT INTO migrations VALUES(15,'2018_07_05_142820_create_categories_table',1);
INSERT INTO migrations VALUES(16,'2018_07_10_055143_create_locales_table',1);
INSERT INTO migrations VALUES(17,'2018_07_20_054502_create_currencies_table',1);
INSERT INTO migrations VALUES(18,'2018_07_20_064849_create_channels_table',1);
INSERT INTO migrations VALUES(19,'2018_07_27_065727_create_products_table',1);
INSERT INTO migrations VALUES(20,'2018_09_20_060658_create_core_config_table',1);
INSERT INTO migrations VALUES(21,'2019_12_14_000001_create_personal_access_tokens_table',1);
INSERT INTO migrations VALUES(22,'2020_12_21_000200_create_channel_translations_table',1);
INSERT INTO migrations VALUES(23,'2020_12_27_121950_create_jobs_table',1);
INSERT INTO migrations VALUES(24,'2021_12_15_104544_notifications',1);
INSERT INTO migrations VALUES(25,'2022_03_15_160510_create_failed_jobs_table',1);
INSERT INTO migrations VALUES(26,'2022_10_04_144444_create_job_batches_table',1);
INSERT INTO migrations VALUES(27,'2024_05_07_111907_create_admins_table',1);
INSERT INTO migrations VALUES(28,'2024_05_07_154640_create_job_instances_table',1);
INSERT INTO migrations VALUES(29,'2024_05_07_154741_create_job_track_table',1);
INSERT INTO migrations VALUES(30,'2024_05_15_204004_create_category_fields',1);
INSERT INTO migrations VALUES(31,'2024_05_15_204039_create_category_fields_translations',1);
INSERT INTO migrations VALUES(32,'2024_05_15_204056_create_category_fields_options',1);
INSERT INTO migrations VALUES(33,'2024_05_15_204106_create_category_fields_options_translations',1);
INSERT INTO migrations VALUES(34,'2024_05_30_120019_create_audits_table',1);
INSERT INTO migrations VALUES(35,'2024_05_30_120020_add_version_id_to_audits_table',1);
INSERT INTO migrations VALUES(36,'2024_05_31_133400_create_audits_trigger',1);
INSERT INTO migrations VALUES(37,'2024_05_31_172638_add_additional_data_column_to_categories_table',1);
INSERT INTO migrations VALUES(38,'2024_06_04_170755_create_attribute_group_translations_table',1);
INSERT INTO migrations VALUES(39,'2024_06_06_175400_create_family_group_mappings',1);
INSERT INTO migrations VALUES(40,'2024_06_14_210156_attribute_family_translations',1);
INSERT INTO migrations VALUES(41,'2024_07_03_185557_create_job_batches_table',1);
INSERT INTO migrations VALUES(42,'2024_07_10_112208_api_keys',1);
INSERT INTO migrations VALUES(43,'2024_07_10_175059_update_id_to_ui_id_oauth_clients',1);
INSERT INTO migrations VALUES(44,'2024_07_10_185855_update_client_id_to_ui_id_oauth_access_tokens',1);
INSERT INTO migrations VALUES(45,'2024_07_10_190001_update_client_id_to_ui_id_oauth_auth_codes',1);
INSERT INTO migrations VALUES(46,'2024_07_10_190040_update_client_id_to_ui_id_oauth_personal_access_clients',1);
INSERT INTO migrations VALUES(47,'2024_07_25_181311_add_filters_column_job_instances',1);
INSERT INTO migrations VALUES(48,'2024_08_12_140143_wk_shopify_credentials_config',1);
INSERT INTO migrations VALUES(49,'2024_08_14_162847_shopify_setting_configuration_value',1);
INSERT INTO migrations VALUES(50,'2024_08_16_163100_add_history_id_to_audits',1);
INSERT INTO migrations VALUES(51,'2024_08_16_173100_update_audits_trigger',1);
INSERT INTO migrations VALUES(52,'2024_08_28_171557_wk_shopify_data_mapping',1);
INSERT INTO migrations VALUES(53,'2024_10_21_123456_modify_filters_column_to_nullable_in_job_instances_table',1);
INSERT INTO migrations VALUES(54,'2024_11_25_173828_create_user_notifications_table',1);
INSERT INTO migrations VALUES(55,'2024_11_25_174212_update_notifications_table',1);
INSERT INTO migrations VALUES(56,'2024_11_27_152754_add_status_column_to_products_table',1);
INSERT INTO migrations VALUES(57,'2024_11_28_174850_migrate_status_value_from_values_column_to_status_column',1);
INSERT INTO migrations VALUES(58,'2025_02_13_165504_add_is_filterable_to_attributes_table',1);
INSERT INTO migrations VALUES(59,'2025_02_17_072844_wk_shopify_metafield_defination',1);
INSERT INTO migrations VALUES(60,'2025_03_18_135047_alter_label_column_type_in_category_field_option_translations_table',1);
INSERT INTO migrations VALUES(61,'2025_03_18_164318_alter_name_column_type_in_category_field_translations_table',1);
INSERT INTO migrations VALUES(62,'2025_03_18_170321_alter_name_column_type_in_attribute_family_translations_table',1);
INSERT INTO migrations VALUES(63,'2025_03_18_170404_alter_name_column_type_in_attribute_group_translations_table',1);
INSERT INTO migrations VALUES(64,'2025_03_18_170449_alter_name_column_type_in_attribute_translations_table',1);
INSERT INTO migrations VALUES(65,'2025_03_18_170603_alter_label_column_type_in_attribute_option_translations_table',1);
INSERT INTO migrations VALUES(66,'2025_05_21_063531_create_magic_prompt_table',1);
INSERT INTO migrations VALUES(67,'2025_06_04_075304_add_ai_translate_to_attributes_table',1);
INSERT INTO migrations VALUES(68,'2025_06_16_182430_create_completeness_settings_table',1);
INSERT INTO migrations VALUES(69,'2025_07_07_182245_create_product_completeness_table',1);
INSERT INTO migrations VALUES(70,'2025_09_05_081733_create_magic_system_prompt_table',1);
INSERT INTO migrations VALUES(71,'2025_09_10_161102_add_avg_completeness_score_column_to_products_table',1);
INSERT INTO migrations VALUES(72,'2025_09_12_060921_add_tone_to_magic_ai_prompts_table',1);
INSERT INTO migrations VALUES(73,'2025_09_20_101519_webhook_logs',1);
INSERT INTO migrations VALUES(74,'2025_09_20_101519_webhook_settings',1);
INSERT INTO migrations VALUES(75,'2025_11_10_150555_alter_column_file_path_set_nullable_to_job_instances',1);
INSERT INTO migrations VALUES(76,'2025_11_10_150556_alter_column_file_path_set_nullable_to_job_track',1);
INSERT INTO migrations VALUES(77,'2026_02_10_000001_create_tenants_table',1);
INSERT INTO migrations VALUES(78,'2026_02_10_000002_add_tenant_id_to_wave1_tables',1);
INSERT INTO migrations VALUES(79,'2026_02_10_000003_add_tenant_id_to_wave2_tables',1);
INSERT INTO migrations VALUES(80,'2026_02_10_000004_add_tenant_id_to_wave3_tables',1);
INSERT INTO migrations VALUES(81,'2026_02_10_000005_make_sku_tenant_unique',1);
INSERT INTO migrations VALUES(82,'2026_02_10_000006_add_is_locked_and_code_to_roles_table',1);
INSERT INTO migrations VALUES(83,'2026_02_11_000007_add_tenant_id_to_wave4_tables',1);
INSERT INTO migrations VALUES(84,'2026_02_11_000008_add_tenant_id_to_wave5_tables',1);
INSERT INTO migrations VALUES(85,'2026_02_11_000009_make_code_columns_tenant_unique',1);
INSERT INTO migrations VALUES(86,'2026_02_13_000010_add_tenant_id_to_wave6_tables',1);
INSERT INTO migrations VALUES(87,'2026_02_14_000011_add_tenant_id_to_wave7_shopify_tables',1);
INSERT INTO migrations VALUES(88,'2026_02_14_000012_make_shopify_columns_tenant_unique',1);
INSERT INTO migrations VALUES(89,'2026_02_14_100001_create_channel_connectors_table',1);
INSERT INTO migrations VALUES(90,'2026_02_14_100002_create_channel_field_mappings_table',1);
INSERT INTO migrations VALUES(91,'2026_02_14_100003_create_channel_sync_jobs_table',1);
INSERT INTO migrations VALUES(92,'2026_02_14_100004_create_product_channel_mappings_table',1);
INSERT INTO migrations VALUES(93,'2026_02_14_100005_create_channel_sync_conflicts_table',1);
INSERT INTO migrations VALUES(94,'2026_02_14_100006_create_webhook_events_table',1);
